name: "02_azure-modules-extraction"
on:
  push:
    branches:
     - main
    paths:
     - 'terraform-modules/azure/**'
jobs:
  Module-Extraction:
    if: "contains(github.event.head_commit.message, 'module is created in the terraform remote repository.')"
    uses: terraform-modules-dwy/terraform-remote-modules/.github/workflows/extractor.yml@main
    with:
      username: terraform-remote-modules
      organization: terraform-modules-dwy
      module_path: 'terraform-modules/azure/'
    secrets:
      APP_ID: ${{secrets.APP_ID}}
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}
